services:
  - type: web
    name: bloodlink
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node start.js
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 